pracaMgr/HorseStable/HorseStable/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from .views import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect),
    path('stable/', include('horses.urls')),
    path('health-card/', include('health_card.urls')),
    path('scheduleitems/', include('scheduleItems.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls'))
    ]

pracaMgr/HorseStable/horses/urls.py
from django.urls import path, include
from .views import create_horse, view_horse, edit_horse, delete_horse, horse_details

app_name = 'horses_url'

urlpatterns = [
    path('create-horse/', create_horse, name='create_horse'),
    path('horses/', view_horse, name='view_horse'),
    path('edit-horse/<int:horse_id>', edit_horse),
    path('delete-horse/<int:horse_id>', delete_horse),
    path('horse-details/<int:horse_id>', horse_details)
]

pracaMgr/HorseStable/scheduleItems/urls.py
from django.urls import path
from .views import create_schedule_item, get_schedule_item
app_name = 'schedule_items_url'

urlpatterns = [
    path('create-scheduleitem/<int:horse_id>', create_schedule_item, name='create_schedule_item'),
    path('scheduleitem/<int:schedule_item_id>', get_schedule_item, name='get_schedule_item')
]

pracaMgr/HorseStable/users/urls.py
from django.urls import path
from .views import register_user
app_name = 'registration'

urlpatterns = [
    path('sign-up', register_user, name='register_user')
]

pracaMgr/HorseStable/horses/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from suplements.models import Suplements
from django.utils.translation import ugettext_lazy as _
from HorseStable.settings import AUTH_USER_MODEL
# Create your models here.
IMAGES_PATH = 'horses/static/images'


class Horses(models.Model):
    MALE = 'Ogier'
    FEMALE = 'Klacz'
    GELDING = 'Wałach'
    SEX_CHOICES = (
        (MALE, _('Ogier')),
        (FEMALE, _('Klacz')),
        (GELDING, _('Wałach'))
    )
    age = models.PositiveSmallIntegerField(
        blank=False,
        null=False,
        validators=[MaxValueValidator(30, message=_('You can enter age below 30 years'))]
    )
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, related_name='horse')
    name = models.CharField(max_length=255, blank=False, null=False)
    breed = models.CharField(max_length=50, blank=True, null=True)
    sex = models.CharField(choices=SEX_CHOICES, max_length=7, default=MALE)
    mother_name = models.CharField(max_length=255, blank=True, null=True)
    father_name = models.CharField(max_length=255, blank=True, null=True)
    photo = models.ImageField(upload_to=IMAGES_PATH, blank=True, null=True)
    suplement = models.ManyToManyField(
        Suplements,
        blank=True,
        related_name='suplements'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "horse"
        verbose_name_plural = "horses"

pracaMgr/HorseStable/horses/forms.py
from django import forms
from horses.models import Horses


class HorseCreationForm(forms.ModelForm):
    class Meta:
        model = Horses
        fields = '__all__'
        widgets = {
            'suplement': forms.widgets.CheckboxSelectMultiple,
            'user': forms.widgets.HiddenInput
        }
        exclude = {'schedule_item'}


class HorseEditForm(forms.ModelForm):
    class Meta:
        model = Horses
        fields = '__all__'
        widgets = {
            'schedule_item': forms.widgets.CheckboxSelectMultiple,
            'suplement': forms.widgets.CheckboxSelectMultiple
        }
        exclude = {'user'}

pracaMgr/HorseStable/horses/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from health_card.models import HealthCard
from .forms import HorseCreationForm, HorseEditForm
from .models import Horses
from django.http import HttpResponse
from django.utils.translation import ugettext_lazy as _
from django.template.defaulttags import register


@login_required
def view_horse(request):
    horses = Horses.objects.filter(user=request.user)
    return render(request, 'crud/read.html', {'horses': horses})


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


@login_required
def horse_details(request, horse_id):
    horse_id = int(horse_id)
    try:
        horse = Horses.objects.get(id=horse_id)
    except Horses.DoesNotExist:
        return HttpResponse(_('Koń nie istnieje'))
    horse_dict = dict()
    for field, value in horse.__dict__.items():
        if field.startswith('_') or field == 'id' or field == 'user_id':
            continue
        horse_dict[field] = value
    suplements = horse.suplement.all
    schedule_items = horse.schedule_item.all
    try:
        health_card = HealthCard.objects.get(horse=horse_id)
    except:
        health_card = "Brak"
    image_path = str(horse.photo)[14:len(horse.photo)] if horse.photo else "None"
    return render(request, 'horse_details.html', {
        'horse': horse,
        'health_card': health_card,
        'suplements': suplements,
        'schedule_items': schedule_items,
        'photo_path': image_path})


@login_required
def create_horse(request):
    form = HorseCreationForm()
    if request.method == 'POST':
        form = HorseCreationForm(request.POST or None)
        if form.is_valid():
            horse_obj = form.save(commit=False)
            horse_obj.user = request.user
            form.save()
            return redirect('horses_url:view_horse')
        else:
            return render(request, 'crud/create.html', {'form': form})
    else:
        return render(request, 'crud/create.html', {'form': form})


@login_required
def edit_horse(request, horse_id):
    horse_id = int(horse_id)
    try:
        horse = Horses.objects.get(id=horse_id)
    except Horses.DoesNotExist:
        return HttpResponse('Koń nie istnieje')
    form = HorseEditForm(request.POST or None, instance=horse)
    if form.is_valid():
        form.save()
        return redirect('horses_url:view_horse')
    return render(request, 'crud/edit.html',
                  {'form': form, 'horse_id': horse.id, 'horse_schedule_item': horse.schedule_item.all()})


@login_required
def delete_horse(request, horse_id):
    horse_id = int(horse_id)
    try:
        horse = Horses.objects.get(id=horse_id)
    except Horses.DoesNotExist:
        return redirect('horses_url:view_horse')
    horse.delete()
    return redirect('horses_url:view_horse')

pracaMgr/HorseStable/horses/templates/crud/create.html
{% extends 'base.html' %}

{% block title %}
Utwórz konia
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Dodaj i zapisz" />
    </form>
{% endblock %}

pracaMgr/HorseStable/horses/templates/crud/edit.html
{% extends 'base.html' %}
{% block body_css %}
<style>
    #id_suplement {
        list-style-type: none;
    }

    input, #id_sex{
        background-color: rgba(214, 229, 250, 0.85);
        border-top: black;
        border-left: black;
        border-right: black;
        border-radius: 10px;
        text-align: center;
        margin-left: 10px;
        font-family: 'Oxygen', sans-serif;
    }

    #id_photo{
        text-align: end;
    }

    #id_sex {
        width: 185px;
        height: 28px;
    }

    #custom-file{
        width: 250px;
    }

</style>
{% endblock %}
{% block title %}
Edycja
{% endblock %}

{% block body %}
    <h1> Formularz edycyjny konia <br>{{ form.name.value }}</h1>
    <form method="post">
        {% csrf_token %}
        <div class="container" id="container_c">
            <div class="row justify-content-md-center">
                    <p style="padding-top: 25px">Wiek: {{ form.age }}</p>
            </div>
            <div class="row justify-content-md-center">
                <p>Imię: {{ form.name }}</p>
            </div>
            <div class="row justify-content-md-center">
                <p>Maść: {{ form.breed }}</p>
            </div>
            <div class="row justify-content-md-center">
                <p>Płeć: {{ form.sex }}</p>
            </div>
            <div class="row justify-content-md-center">
                <p>Imię matki:{{ form.mother_name }}</p>
            </div>
            <div class="row justify-content-md-center">
                <p>Imię ojca: {{ form.father_name }}</p>
            </div>
            <div class="row justify-content-md-center">
                <p hidden="hiden">Zdjęcie: {{ form.photo }}</p>
                <p>Zdjęcie: <input class="btn btn-success" value="Kliknij aby wybrać nowy plik" id="custom-file"></p>
            </div>
            <div class="row justify-content-md-center">
                <p>Suplementacja: {{ form.suplement }}</p>
            </div>
        </div>
            {% for schedule_item in horse_schedule_item %}
                <p> {{ schedule_item.title }} {{ schedule_item.dueDate|date:'d/m/Y' }} {{ schedule_item.dueTime|time:'H:i:s' }}</p>
            {% empty %}
                <p>Brak wydarzeń</p>
            {% endfor %}

        <a class="btn btn-primary" href="{% url 'schedule_items_url:create_schedule_item' horse_id=horse_id%}">Dodaj nowe wydarzenie</a>
        <br>
        <br>
        <input class="btn btn-primary" type="submit" value="Zapisz zmiany" />
    </form>

    <script type="text/javascript">
        const realPhotoClick = document.getElementById("id_photo")
        const customButton = document.getElementById("custom-file")
        customButton.addEventListener("click", function () {
            realPhotoClick.click()
        })
    </script>
{% endblock %}

pracaMgr/HorseStable/horses/templates/crud/read.html
{% extends 'base.html' %}

{% block title %}
Spis koni
{% endblock %}
{% block body_css %}
    <style>
    h1 {
        text-align: center;
        padding-bottom: 50px;
        padding-top: 50px;
        font-size: 70px;
    }

    li {
        text-align: center;
        font-weight: bold;
        color: black;
        background-color: rgba(250, 235, 215, 0.85);
    }

    </style>
{% endblock %}
{% block body %}
    <h1> Witaj, {{ user.first_name }} {{ user.last_name }}. <br>Oto spis Twoich koni. </h1>
    <ul style="list-style-type: none">
    <div class="container">
        <div class="row justify-content-md-center">
            {% for horse in horses %}

            <div class="col-md-auto">
                <li style="border-top-left-radius: 25px; border-top-right-radius: 25px"> Imię: {{ horse.name }} </li>
                <li> Wiek: {{ horse.age }} </li>
                {% if horse.breed != None %}
                    <li> Maść: {{ horse.breed }}</li>
                {% else %}
                <li> Maść: Brak</li>
                {% endif %}
                <a class="btn btn-info" href="/stable/edit-horse/{{ horse.id }}">Edytuj konia</a>
                <a class="btn btn-danger" href="/stable/delete-horse/{{ horse.id }}">Usuń konia</a>
                <a class="btn btn-info" href="/stable/horse-details/{{ horse.id }}">Szczegóły</a>
            </div>
            {% if forloop.counter|divisibleby:3%}
                </div>
                <br>
                <div class="row justify-content-md-center">

            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% block main_page %}
    <br>
    {% endblock %}
    <br>
    <div style="text-align: center">
    <a class="btn btn-info" href="{% url 'horses_url:create_horse' %}">Dodaj nowego konia</a>
    {% if user.is_authenticated %}
        <a class="btn btn-warning" href="{% url 'logout' %}">Wyloguj się</a>
    {% endif %}
    </div>
</ul>
{% endblock %}