pracaMgr/HorseStable/HorseStable/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from .views import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect),
    path('stable/', include('horses.urls')),
    path('health-card/', include('health_card.urls')),
    path('scheduleitems/', include('scheduleItems.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls'))
    ]

pracaMgr/HorseStable/health_card/urls.py
from django.urls import path
from .views import create_health_card, get_health_card, create_health_card_record

app_name = 'health_card_urls'

urlpatterns = [
    path('create-health-card/<int:horse_id>', create_health_card, name='create_health_card'),
    path('<int:healthcard_id>/', get_health_card, name='get_health_card'),
    path('health-card-<int:horse_id>/create-record', create_health_card_record, name='create_healthcard_record')
]

pracaMgr/HorseStable/users/urls.py
from django.urls import path
from .views import register_user
app_name = 'registration'

urlpatterns = [
    path('sign-up', register_user, name='register_user')
]

pracaMgr/HorseStable/health_card/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from horses.models import Horses


class HealthCard(models.Model):
    horse = models.OneToOneField(Horses, on_delete=models.CASCADE, blank=False, null=True, related_name='health_card', default=None)

    def __str__(self):
        return self.horse.name

    class Meta:
        verbose_name = 'health card'
        verbose_name_plural = 'health cards'


class HealthCardRecord(models.Model):
    VACCINATION = 'VCC'
    NOURISHMENT = 'NRH'
    MEDICINE = 'MDC'
    HCTYPE_CHOICES = (
        (VACCINATION, _('Vaccination')),
        (NOURISHMENT, _('Nourishment')),
        (MEDICINE, _('Medicine'))
    )

    description = models.CharField(max_length=100, blank=False, null=False)
    date = models.DateField(blank=False, null=False)
    type = models.CharField(choices=HCTYPE_CHOICES, max_length=3)
    health_card = models.ForeignKey(HealthCard, on_delete=models.CASCADE, related_name='health_card_record')

    def __str__(self):
        return f'{self.type} | {self.description}'

    class Meta:
        verbose_name = 'health card record'
        verbose_name_plural = 'health card records'

pracaMgr/HorseStable/health_card/forms.py
from django import forms
from health_card.models import HealthCard, HealthCardRecord


class HealthCardCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        actual_horse_id = kwargs.pop('horse_id')
        super().__init__()
        self.fields['horse'].initial = actual_horse_id

    class Meta:
        model = HealthCard
        fields = '__all__'


class HealthCardRecordCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        actual_horse_health_card = kwargs.pop('health_card')
        super().__init__(*args, **kwargs)
        self.fields['health_card'].initial = actual_horse_health_card

    class Meta:
        model = HealthCardRecord
        fields = '__all__'

pracaMgr/HorseStable/health_card/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import HealthCard, HealthCardRecord
from django.utils.translation import ugettext_lazy as _
from horses.models import Horses
from health_card.forms import HealthCardCreationForm, HealthCardRecordCreationForm


def get_health_card(request, healthcard_id):
    horse_hc = Horses.objects.get(health_card=healthcard_id)
    try:
        health_card = HealthCard.objects.get(id=healthcard_id)
        health_card_records = HealthCardRecord.objects.filter(health_card=health_card)
    except HealthCard.DoesNotExist:
        return HttpResponse(_('Karta zdrowia nie istnieje'))
    return render(request, 'crud/health_card.html', {'health_card': horse_hc,
                                                     'health_card_records': health_card_records})


def create_health_card(request, horse_id):
    #TODO czemu nie działaaaaaaa
    form = HealthCardCreationForm(horse_id=horse_id)
    if request.method == 'POST':
        form = HealthCardCreationForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect(reverse('get_health_card'), kwargs={'healthcard_id': form['horse'].health_card})
        else:
            return render(request, 'crud/create_health_card.html', {'form': form})
    else:
        return render(request, 'crud/create_health_card.html', {'form': form})


def create_health_card_record(request, horse_id):
    health_card = HealthCard.objects.get(horse=horse_id)
    form = HealthCardRecordCreationForm(health_card=health_card)
    if request.method == 'POST':
        form = HealthCardRecordCreationForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect(reverse('health_card_urls:get_health_card', kwargs={'healthcard_id': health_card.id}))
        else:
            return render(request, 'crud/create_healthcard_record.html', {'form': form})
    else:
        return render(request, 'crud/create_healthcard_record.html', {'form': form, 'health_card': health_card})

pracaMgr/HorseStable/health_card/templates/crud/create_health_card.html
{% extends 'base.html' %}
{% block title %}
Utwórz kartę zdrowia
{% endblock %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Dodaj i zapisz" />
    </form>
{% endblock %}

pracaMgr/HorseStable/health_card/templates/crud/create_healthcard_record.html
{% extends 'base.html' %}
{% block title %}
    Utwórz rekord do karty zdrowia
{% endblock %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Dodaj i zapisz" />
    </form>
{% endblock %}

pracaMgr/HorseStable/health_card/templates/crud/health_card.html
{% extends 'base.html' %}

{% block title %}
     Karta zdrowia - {{ health_card.name }}
{% endblock %}

{% block body %}
    <table>

        <tr>
            <th>Typ</th>
            <th>Data</th>
            <th>Opis</th>
        </tr>
        {% if health_card_records %}
            {% for record in health_card_records %}
            <tr>
                <td>{{ record.type }}</td>
                <td>{{ record.date }}</td>
                <td>{{ record.description }}</td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td> Brak rekordów </td>
            </tr>
        {% endif %}
        <tr>
            <td><a class="btn btn-primary" href="{% url 'health_card_urls:create_healthcard_record' horse_id=health_card.id%}">Dodaj rekord</a></td>
        </tr>
    </table>
{% endblock %}