pracaMgr/HorseStable/HorseStable/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from .views import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect),
    path('stable/', include('horses.urls')),
    path('health-card/', include('health_card.urls')),
    path('scheduleitems/', include('scheduleItems.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls'))
    ]

pracaMgr/HorseStable/health_card/urls.py
from django.urls import path
from .views import create_health_card, get_health_card, create_health_card_record

app_name = 'health_card_urls'

urlpatterns = [
    path('create-health-card/<int:horse_id>', create_health_card, name='create_health_card'),
    path('<int:healthcard_id>/', get_health_card, name='get_health_card'),
    path('health-card-<int:horse_id>/create-record', create_health_card_record, name='create_healthcard_record')
]

pracaMgr/HorseStable/horses/urls.py
from django.urls import path, include
from .views import create_horse, view_horse, edit_horse, delete_horse, horse_details

app_name = 'horses_url'

urlpatterns = [
    path('create-horse/', create_horse, name='create_horse'),
    path('horses/', view_horse, name='view_horse'),
    path('edit-horse/<int:horse_id>', edit_horse),
    path('delete-horse/<int:horse_id>', delete_horse),
    path('horse-details/<int:horse_id>', horse_details)
]

pracaMgr/HorseStable/users/urls.py
from django.urls import path
from .views import register_user
app_name = 'registration'

urlpatterns = [
    path('sign-up', register_user, name='register_user')
]

pracaMgr/HorseStable/horses/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from suplements.models import Suplements
from django.utils.translation import ugettext_lazy as _
from HorseStable.settings import AUTH_USER_MODEL
# Create your models here.
IMAGES_PATH = 'horses/static/images'


class Horses(models.Model):
    MALE = 'Ogier'
    FEMALE = 'Klacz'
    GELDING = 'Wałach'
    SEX_CHOICES = (
        (MALE, _('Ogier')),
        (FEMALE, _('Klacz')),
        (GELDING, _('Wałach'))
    )
    age = models.PositiveSmallIntegerField(
        blank=False,
        null=False,
        validators=[MaxValueValidator(30, message=_('You can enter age below 30 years'))]
    )
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, related_name='horse')
    name = models.CharField(max_length=255, blank=False, null=False)
    breed = models.CharField(max_length=50, blank=True, null=True)
    sex = models.CharField(choices=SEX_CHOICES, max_length=7, default=MALE)
    mother_name = models.CharField(max_length=255, blank=True, null=True)
    father_name = models.CharField(max_length=255, blank=True, null=True)
    photo = models.ImageField(upload_to=IMAGES_PATH, blank=True, null=True)
    suplement = models.ManyToManyField(
        Suplements,
        blank=True,
        related_name='suplements'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "horse"
        verbose_name_plural = "horses"

pracaMgr/HorseStable/horses/forms.py
from django import forms
from horses.models import Horses


class HorseCreationForm(forms.ModelForm):
    class Meta:
        model = Horses
        fields = '__all__'
        widgets = {
            'suplement': forms.widgets.CheckboxSelectMultiple,
            'user': forms.widgets.HiddenInput
        }
        exclude = {'schedule_item'}


class HorseEditForm(forms.ModelForm):
    class Meta:
        model = Horses
        fields = '__all__'
        widgets = {
            'schedule_item': forms.widgets.CheckboxSelectMultiple,
            'suplement': forms.widgets.CheckboxSelectMultiple
        }
        exclude = {'user'}

pracaMgr/HorseStable/horses/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from health_card.models import HealthCard
from .forms import HorseCreationForm, HorseEditForm
from .models import Horses
from django.http import HttpResponse
from django.utils.translation import ugettext_lazy as _
from django.template.defaulttags import register


@login_required
def view_horse(request):
    horses = Horses.objects.filter(user=request.user)
    return render(request, 'crud/read.html', {'horses': horses})


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


@login_required
def horse_details(request, horse_id):
    horse_id = int(horse_id)
    try:
        horse = Horses.objects.get(id=horse_id)
    except Horses.DoesNotExist:
        return HttpResponse(_('Koń nie istnieje'))
    horse_dict = dict()
    for field, value in horse.__dict__.items():
        if field.startswith('_') or field == 'id' or field == 'user_id':
            continue
        horse_dict[field] = value
    suplements = horse.suplement.all
    schedule_items = horse.schedule_item.all
    try:
        health_card = HealthCard.objects.get(horse=horse_id)
    except:
        health_card = "Brak"
    image_path = str(horse.photo)[14:len(horse.photo)] if horse.photo else "None"
    return render(request, 'horse_details.html', {
        'horse': horse,
        'health_card': health_card,
        'suplements': suplements,
        'schedule_items': schedule_items,
        'photo_path': image_path})


@login_required
def create_horse(request):
    form = HorseCreationForm()
    if request.method == 'POST':
        form = HorseCreationForm(request.POST or None)
        if form.is_valid():
            horse_obj = form.save(commit=False)
            horse_obj.user = request.user
            form.save()
            return redirect('horses_url:view_horse')
        else:
            return render(request, 'crud/create.html', {'form': form})
    else:
        return render(request, 'crud/create.html', {'form': form})


@login_required
def edit_horse(request, horse_id):
    horse_id = int(horse_id)
    try:
        horse = Horses.objects.get(id=horse_id)
    except Horses.DoesNotExist:
        return HttpResponse('Koń nie istnieje')
    form = HorseEditForm(request.POST or None, instance=horse)
    if form.is_valid():
        form.save()
        return redirect('horses_url:view_horse')
    return render(request, 'crud/edit.html',
                  {'form': form, 'horse_id': horse.id, 'horse_schedule_item': horse.schedule_item.all()})


@login_required
def delete_horse(request, horse_id):
    horse_id = int(horse_id)
    try:
        horse = Horses.objects.get(id=horse_id)
    except Horses.DoesNotExist:
        return redirect('horses_url:view_horse')
    horse.delete()
    return redirect('horses_url:view_horse')

pracaMgr/HorseStable/horses/templates/horse_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Szczegóły {{ horse.name }}
{% endblock %}

{% block body %}
    <h1>Szczegóły konia {{ horse.name }}</h1>
    <div class="container" id="container_c">
    {% if photo_path != "None" %}
        <div class="row justify-content-around" style="padding-top: 25px; padding-bottom: 10px">
            <div class="col-md-auto">
                <div class="row justify-content-md-center">
                    <p>Nazwa: {{ horse.name }}</p>
                </div>
                <div class="row justify-content-md-center">
                    <p>Maść: {{ horse.breed }}</p>
                </div>
                <div class="row justify-content-md-center">
                    <p>Płeć: {{ horse.sex }}</p>
                </div>
                <div class="row justify-content-md-center">
                    {% if health_card != 'Brak' %}
                        <p>Karta zdrowia: <a href="{% url 'health_card_urls:get_health_card' healthcard_id=horse.health_card.id %}">{{ horse.health_card }}</a></p>
                    {% else %}
                        <p>Karta zdrowia: <a href="{% url 'health_card_urls:create_health_card' horse_id=horse.id %}">Utwórz kartę zdrowia</a></p>
                    {% endif %}
                </div>
                <div class="row justify-content-md-center">
                    {% if horse.mother_name != 'None' %}
                        <p>Imię matki: Brak</p>
                    {% else %}
                        <p>Imię matki: {{ horse.mother_name }}</p>
                    {% endif %}
                </div>
                <div class="row justify-content-md-center">
                    {% if horse.father_name != 'None' %}
                        <p>Imię ojca: Brak</p>
                    {% else %}
                        <p>Imię ojca: {{ horse.father_name }}</p>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-auto">
                <img alt="Image" src="{% static photo_path %}">
            </div>

        </div>
        <div class="row justify-content-around">
            <div class="col-md-auto">
            <p>Suplementy:</p>
                {% for suplement in suplements %}
                    <div class="row justify-content-md-center"><p>{{ suplement.suplement_name }}</p></div>
                {% empty %}
                    <div class="row justify-content-md-center"><p>Brak przypisanych suplementów</p></div>
                {% endfor %}
            </div>
            <div class="col-md-auto">
            <p>Wydarzenia:</p>
                {% for schedule_item in horse.schedule_item.all %}
                    <div class="row justify-content-md-center"><p>{{ schedule_item.title }}</p></div>
                {% empty %}
                    <div class="row justify-content-md-center"><p>Brak przypisanych wydarzeń</p></div>
                {% endfor %}
            </div>
        </div>
        {% else %}
        <div class="row justify-content-around" style="padding-top: 25px; padding-bottom: 10px">
            <div class="col-md-auto">
                <div class="row justify-content-md-center">
                    <p>Nazwa: {{ horse.name }}</p>
                </div>
                <div class="row justify-content-md-center">
                    <p>Maść: {{ horse.breed }}</p>
                </div>
                <div class="row justify-content-md-center">
                    <p>Płeć: {{ horse.sex }}</p>
                </div>
                {% if health_card != "Brak" %}
                    <p>Karta zdrowia: <a href="{% url 'health_card_urls:get_health_card' healthcard_id=horse.health_card.id %}">{{ horse.health_card }}</a></p>
                {% else %}
                    <p>Karta zdrowia: <a href="{% url 'health_card_urls:create_health_card' horse_id=horse.id %}">Utwórz kartę zdrowia</a></p>
                {% endif %}
                <div class="row justify-content-md-center">
                    {% if horse.mother_name != 'None' %}
                        <p>Imię matki: Brak</p>
                    {% else %}
                        <p>Imię matki: {{ horse.mother_name }}</p>
                    {% endif %}
                </div>
                <div class="row justify-content-md-center">
                    {% if horse.father_name != 'None' %}
                        <p>Imię ojca: Brak</p>
                    {% else %}
                        <p>Imię ojca: {{ horse.father_name }}</p>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-auto">
                <div class="row justify-content-md-center">
                    <p>Suplementy:</p>
                </div>
                {% for suplement in suplements %}
                    <div class="row justify-content-md-center"><p>{{ suplement.suplement_name }}</p></div>
                {% empty %}
                    <div class="row justify-content-md-center"><p>Brak przypisanych suplementów</p></div>
                {% endfor %}
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-auto">
                <p>Wydarzenia:</p>
                {% for schedule_item in horse.schedule_item.all %}
                    <div class="row justify-content-md-center"><p>{{ schedule_item.title }}</p></div>
                {% empty %}
                    <div class="row justify-content-md-center"><p>Brak przypisanych wydarzeń</p></div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    </div>


{% endblock %}